name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: |
        sudo apt update
        sudo apt install -y libboost-all-dev
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure --enable-test
    - name: make
      run: make -j 20
    - name: make check
      run: make check -j 20 || more test/unix/test-suite.log
